#
# A Bookstore example API configuration.
#
# Below, replace MY_PROJECT_ID with your Google Cloud Project ID.
#

# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
# Replcate <YOUR_PROJECT_ID> by your own GCP Project ID
#
name: player.endpoints.<YOUR_PROJECT_ID>.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: Player gRPC API
apis:
- name: player.Player

#
# API usage restrictions.
#
usage:
  rules:
  # Allow unregistered calls for all methods.
  - selector: "*"
    allow_unregistered_calls: true