# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

# Name of the service configuration.
# Replace PROJECT_ID with the ID of your GCP project:
name: player.endpoints.PROJECT_ID.cloud.goog

# API title to appear in the user interface (Google Cloud Console).
title: Player gRPC API
apis:
- name: player.Player

# API usage restrictions.
usage:
  rules:
  # Allow unregistered calls for all methods. This is mandatory for using quotas
  - selector: "*"
    allow_unregistered_calls: true